version: "3"
services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    container_name: selenoid
    network_mode: bridge
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-limit", "3", "-retry-count", "1000", "-session-attempt-timeout", "3m", "-service-startup-timeout", "3m"]
    ports:
      - 4444:4444
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/ui-test/src/main/resources:/etc/selenoid"
      - "$PWD/selenoid/video:/opt/selenoid/video"
      - "$PWD/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR="$PWD/selenoid/video"
      - TZ=Europe/Berlin
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.4.3"
    container_name: selenoid-ui
    network_mode: bridge
    command: -selenoid-uri 'http://selenoid:4444'
    ports:
      - 9090:8080
    links:
      - selenoid
  test-mobilab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-automation
    network_mode: bridge
    volumes:
      - ${PWD}/report/api-test/results:/app/api-test/target/allure-results
      - ${PWD}/report/api-test/reports:/app/api-test/target/allure-reports
      - ${PWD}/report/api-test/logs:/app/api-test/logs
      - ${PWD}/report/ui-test/results:/app/ui-test/target/allure-results
      - ${PWD}/report/ui-test/reports:/app/ui-test/target/allure-reports
      - ${PWD}/report/ui-test/logs:/app/ui-test/logs
    links:
      - selenoid
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: "TRUE"
      KEEP_HISTORY_LATEST: 10
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/report:/app/projects
